var parks=[
  {id:'mk',maps:{official:'https://mickeyvisit.com/disney-world-magic-kingdom-map/',pdf:'https://disneyworld.disney.go.com/media/wdw_nextgen/CoreCatalog/WaltDisneyWorld/en_us/PDF/magic-kingdom-park-map.pdf',gmaps:'https://maps.google.com/maps?q=Magic+Kingdom+Walt+Disney+World+Orlando+FL&output=embed&z=16'},name:'Magic Kingdom',
   tag:'Best park for almost-4 · Princesses · Classic gentle rides · Villains Land coming ~2031',
   hbg:'#7D7ABC',htxt:'#ffffff',
   pills:['10 rides she can do','Princess castle','Bibbidi Bobbidi Boutique'],
   age:'Magic Kingdom is the best park for this age. The vast majority of rides have no height requirement and were designed for kids 2–5. Plan a full day and return in the evening for the fireworks.',
   coming:'Villains Land is under active construction "beyond Big Thunder Mountain" and will be Magic Kingdom\'s biggest ever expansion — two major rides, dining, and shopping inspired by Disney Animation villains including Maleficent, Ursula, Hades, and Dr. Facilier. It is expected to open around 2030–2031, so it will likely not be open for your 2029 trip — but construction will be visible and the excitement is real. Also coming nearby: Piston Peak, a new Cars-themed land. Magic Kingdom is in the middle of its most dramatic transformation since opening.',
   day:['Rope drop → Fantasyland first: Peter Pan, Dumbo, Winnie the Pooh, Small World (lines triple by 9:30am)','Mid-morning: Buzz Lightyear Space Ranger Spin, Tomorrowland Speedway (she rides with you)','Afternoon: Pirates of the Caribbean, Jungle Cruise, Haunted Mansion (assess her reaction to darkness)','Early evening: dinner reservation → position on Main Street for Happily Ever After fireworks'],
   night:['Happily Ever After fireworks + Cinderella Castle projections — the best show at all of WDW','Disney Starlight: Dream the Night Away — the new nighttime parade that opened 2025 · Runs twice nightly on Main Street','Main Street glows with lanterns after the show — stroll slowly toward the exit'],
   rAll:[
     {n:"Peter Pan's Flight",nt:"No height req · Must-do for little girls — flying over London at night · She will ask to go again"},
     {n:'Dumbo the Flying Elephant',nt:'No height req · Classic · She controls how high to fly · Perfect for this age'},
     {n:'Many Adventures of Winnie the Pooh',nt:'No height req · Sweet and gentle · Excellent for almost-4'},
     {n:'"it\'s a small world"',nt:'No height req · Calm bright boat through singing dolls — toddler heaven'},
     {n:"Buzz Lightyear's Space Ranger Spin",nt:'No height req · Laser-shooting interactive ride · You can help her aim · Newly enhanced 2026'},
     {n:'Pirates of the Caribbean',nt:'No height req · Gentle boat ride · Mildly dark caves at the start'},
     {n:'Jungle Cruise',nt:'No height req · Silly jokes and fake animals · Grandma will love it too'},
     {n:'Walt Disney World Railroad',nt:'No height req · Train circles the whole park · Great rest for tired legs'},
     {n:'Tomorrowland Speedway',nt:'32" to ride with adult · She gets to help steer'},
     {n:'Carousel of Progress',nt:'No height req · Sit-down show · Great air-conditioned rest break'},
   ],
   snacks:[
     {n:"LeFou's Brew",w:"Gaston's Tavern",p:'$~6',nt:"Frozen apple juice + passion fruit boba — kid and adult favourite · She'll love the boba balls"},
     {n:'Warm Cinnamon Roll',w:"Gaston's Tavern",p:'$~9',nt:'Giant and gooey · One feeds the whole family · Get it at rope drop'},
     {n:'Dole Whip',w:'Aloha Isle',p:'$~6',nt:'Frozen pineapple soft serve · A Disney legend · She will want one every day'},
     {n:'Cheeseburger Spring Rolls',w:'Near Adventureland cart',p:'$~10',nt:'Cult-favourite savoury snack for the adults'},
     {n:'Mickey Premium Ice Cream Bar',w:'Carts everywhere',p:'$~7',nt:'The classic · Do it at least once · Great photo moment'},
   ],
   rests:[
     {n:'Be Our Guest',t:'ts',p:'~$120–$160',nt:"Beauty & the Beast castle dining · Dinner most magical · Book the moment your 60-day window opens"},
     {n:'The Crystal Palace',t:'ts',p:'~$140–$180',nt:'Winnie the Pooh + Piglet + Eeyore + Tigger · Buffet so she can choose · Perfect for almost-4'},
     {n:'Columbia Harbour House',t:'qs',p:'~$60–$70',nt:'Best QS in MK · Clam chowder, lobster roll · Cozy indoor seating'},
   ],
   shops:[
     {section:'For your little girl'},
     {n:'Bibbidi Bobbidi Boutique',nt:'Already planned! Inside the castle · At almost 4 this will be the highlight of her whole trip'},
     {n:"Sir Mickey's",nt:'Near the castle · Best character merch — tiaras, wands, princess dresses'},
     {n:'Castle Couture',nt:'Right in Fantasyland · Disney Princess-themed clothing, accessories, and gifts · Closer to the castle than Sir Mickey\'s · Great for a quick princess haul'},
     {n:"Tiana's Bayou General",nt:"Exit shop from Tiana's Bayou Adventure · Tiana-themed treats, apparel, and souvenirs · New merch tied to the 2023 ride update"},
     {n:'Fantasyland boutiques',nt:'Multiple small shops around the castle with costumes, accessories, and plush'},
     {section:'For adults'},
     {n:'The Beak and Barrel',nt:"Adventureland · Magic Kingdom's first-ever bar, opened August 2025 · Pirates of the Caribbean-themed lounge · Cocktails, mocktails, small bites · Interactive character Rummy patrols the bar · 45-min sittings, reservations essential · Book at your 60-day window — fills fast"},
     {n:'Memento Mori',nt:'Liberty Square · Haunted Mansion-themed merchandise · Apparel, home goods, collectibles from the Haunted Mansion Authentic program · A genuinely great adult shop — items are limited and sell out'},
     {n:'Tomorrowland Launch Depot',nt:'TRON Identity Program ($89) — customize your own TRON action figure with your choice of style and voice · Also carries TRON apparel, Star Wars, Grogu plush, Space Mountain merch'},
     {n:'Prairie Outpost & Supply',nt:'Frontierland · Reopened June 2025 · Chapel Hats partner store — wide-brimmed hats, classic fedoras, and custom headwear · Great souvenir that actually gets worn after the trip'},
     {n:'The Emporium',nt:'Main Street · Largest shop in MK · Classic merch, pin trading, exclusive MK items · Good for ears, Loungefly bags, and last-minute gifts'},
     {n:'Main Street Confectionery',nt:'Candy apples, fudge, chocolate-dipped treats · Great end-of-night stop · Watch the fudge being made through the window'},
   ]
  },
  {id:'ep',maps:{official:'https://mickeyvisit.com/disney-world-epcot-map/',pdf:'https://mickeyvisit.com/disney-world-epcot-map/',gmaps:'https://maps.google.com/maps?q=EPCOT+Walt+Disney+World+Orlando+FL&output=embed&z=16'},name:'EPCOT',
   tag:'Frozen · Remy · World Showcase · Best food at Disney',
   hbg:'#1ABFA4',htxt:'#ffffff',
   pills:['Frozen Ever After','World Showcase food','Elsa & Anna meet'],
   age:"EPCOT has fewer toddler-specific rides than Magic Kingdom but Frozen Ever After and Remy alone justify a full day. Treat the World Showcase as an afternoon food adventure — at almost 4 she will happily wander and taste things.",
   coming:null,
   festivals:[
     {name:'Festival of the Arts',months:'Early Jan — mid-Feb',color:'#7D7ABC',nt:'Visual, culinary, and performing arts throughout the park · Food studios inspired by famous artworks · Broadway-style performances on the America Gardens Theatre stage · One of the least-crowded times to visit EPCOT'},
     {name:'Flower & Garden Festival',months:'Early Mar — early Jun',color:'#1ABFA4',nt:'Disney character topiaries throughout World Showcase · Outdoor Kitchen food booths with spring-inspired menus · Butterfly gardens and hummingbird habitats · Arguably the most beautiful EPCOT looks all year'},
     {name:'Food & Wine Festival',months:'Late Aug — mid-Nov',color:'#EF767A',nt:"The most popular EPCOT festival · 30+ food booths around World Showcase serving global dishes · Live music most evenings on the America Gardens stage · Book the park early if your trip falls in this window — it's the busiest EPCOT gets"},
     {name:'Festival of the Holidays',months:'Mid-Nov — early Jan',color:'#D4A800',nt:"Holiday traditions from countries around World Showcase · Candlelight Processional with celebrity narrators · Cookies & Cocoa with Santa · EPCOT's most atmospheric time of year — the whole park feels transformed"},
   ],
   day:['Rope drop → Frozen Ever After immediately (lines hit 60+ mins by 9am — sprint here first)',"Remy's Ratatouille Adventure → Spaceship Earth → The Seas with Nemo & Friends",'Mid-morning: adults use Lightning Lane for Guardians + Soarin\' while she explores with the other adult','Afternoon: World Showcase stroll — try food from 3–4 countries · Find Elsa and Anna in Norway pavilion'],
   night:['World Showcase illuminated at night — the most beautiful strolling experience at all of WDW','Luminous: The Symphony of Us fireworks at 9pm over World Showcase Lagoon','Late-night crepe from France pavilion · EPCOT festival booths transform the park if your timing aligns'],
   rAll:[
     {n:'Frozen Ever After',nt:"No height req · She will completely lose her mind · Full Elsa & Anna immersion · Ride twice if possible"},
     {n:"Remy's Ratatouille Adventure",nt:"No height req · Trackless ride through Gusteau's kitchen · Very sweet, not scary"},
     {n:'Spaceship Earth',nt:'No height req · Slow gentle history journey · Great for grandma · Good rest ride'},
     {n:'The Seas with Nemo & Friends',nt:"No height req · Clamshell ride through a real aquarium · She'll recognise Nemo and Dory"},
     {n:'Journey Into Imagination with Figment',nt:'No height req · Fun and slightly unpredictable · Some kids love Figment, some are nervous'},
     {n:'Living with the Land',nt:"No height req · Peaceful boat through Disney's real greenhouses · Very calm rest option"},
   ],
   snacks:[
     {n:'School Bread',w:'Kringla Bakeri og Kafé, Norway',p:'$~6',nt:'Cardamom bun + vanilla custard + coconut · A Disney legend'},
     {n:'Macaron ice cream sandwich',w:"L'Artisan des Glaces, France",p:'$~9',nt:'Two macarons + ice cream · Beautiful and delicious'},
     {n:'Baguette',w:'Les Halles, France',p:'$~4',nt:'Half-baguette · Best value snack in all of Disney'},
     {n:'Caramel apple slice',w:'Karamell-Küche, Germany',p:'$~6',nt:'Fresh apple + caramel · Great for sharing with little hands'},
   ],
   rests:[
     {n:'Akershus Royal Banquet Hall',t:'ts',p:'~$160–$200',nt:'Princess character dining in Norway · Meets multiple princesses · Book early'},
     {n:'Coral Reef Restaurant',t:'ts',p:'~$120–$160',nt:"Dining inside the aquarium · Fish swim past the window · She'll press her nose to the glass the whole meal"},
     {n:'Sunshine Seasons',t:'qs',p:'~$55–$65',nt:'In The Land pavilion · Freshest, healthiest QS at WDW · Good grandma-friendly options'},
   ],
   shops:[
     {section:'For your little girl'},
     {n:'Norway Pavilion',nt:'Frozen merch everywhere · Meet Elsa + Anna here · Best shop in EPCOT for small girls'},
     {n:'France Pavilion',nt:"Remy plush after the ride · She'll want a little Remy to take home"},
     {n:'UK Pavilion',nt:'Alice in Wonderland, Winnie the Pooh · Charming kids items'},
     {section:'For adults'},
     {n:'Karamell-Küche',nt:'Germany · Caramel apple slices, caramel corn, pretzel rods — everything caramel'},
     {n:'La Maison du Vin',nt:"France · French wines and gourmet pantry items · Good gifts to bring home"},
     {n:'Mouse Gear',nt:"Largest EPCOT shop · EPCOT-exclusive merch you can't get elsewhere"},
   ]
  },
  {id:'hs',maps:{official:'https://mickeyvisit.com/disney-world-hollywood-studios-map/',pdf:'https://mickeyvisit.com/disney-world-hollywood-studios-map/',gmaps:'https://maps.google.com/maps?q=Disney+Hollywood+Studios+Walt+Disney+World+Orlando+FL&output=embed&z=16'},name:'Hollywood Studios',
   tag:'Star Wars · Villains show · Toy Story · Fantasmic! · Monstropolis coming',
   hbg:'#EF767A',htxt:'#ffffff',
   pills:["Galaxy's Edge","Villains: Unfairly Ever After","Savi's Workshop"],
   age:"Hollywood Studios has only two no-height-requirement rides, but Galaxy's Edge is one of the most immersive environments ever built — even at almost 4 she will be transfixed by the Millennium Falcon, stormtroopers on patrol, and the alien landscape. The villain show (Cruella! Maleficent! Captain Hook!) is great for the whole family. Plan a half-to-full day.",
   coming:"Monstropolis is under construction at Hollywood Studios — a Monsters, Inc. themed land with a suspended roller coaster, the first of its kind at Disney. No confirmed opening date yet but it could be open by 2029. Worth watching.",
   day:["Rope drop → Mickey & Minnie's Runaway Railway immediately (most popular, fills very fast)",'Toy Story Land: Toy Story Mania then Alien Swirling Saucers (32" — measure her before the trip)','Mid-morning: Disney Villains: Unfairly Ever After — the villain stage show with Cruella, Captain Hook, and Maleficent · Great for the whole family · She will love the costumes',"Afternoon: Galaxy's Edge for the rest of the day · Oga's Cantina for the adults · Docking Bay 7 for dinner",'Evening: Fantasmic! — book a dining package or queue very early'],
   night:["Fantasmic! — Mickey's dream sequence with fire, fountains, and characters · One of the best shows at WDW",'Galaxy\'s Edge glows completely at night — the Millennium Falcon lit up against a dark sky is jaw-dropping · Stormtroopers patrol after dark','Stay for the last hour — crowds thin and Galaxy\'s Edge feels almost private'],
   rAll:[
     {n:"Mickey & Minnie's Runaway Railway",nt:"No height req · Trackless, funny, visually incredible · Top priority at rope drop"},
     {n:'Toy Story Mania!',nt:"No height req · Carnival game shooting ride · She'll love competing with the family"},
     {n:'Alien Swirling Saucers',nt:'32" — borderline, measure her before the trip · Fun spinning ride with Little Green Men if she clears it'},
     {n:'Disney Villains: Unfairly Ever After',nt:"Show · No height req · Cruella De Vil, Captain Hook, and Maleficent tell their side of the story · Opened May 2025 · Great for the whole family · She will love the dramatic costumes"},
     {n:'The Little Mermaid — A Musical Adventure',nt:"Show · No height req · Full reimagined Little Mermaid stage show · Opened May 2025 · She will be enchanted"},
   ],
   snacks:[
     {n:'Ronto Wrap',w:"Ronto Roasters, Galaxy's Edge",p:'$~15',nt:"Roasted pork + pork sausage in warm pita · One of the best QS items at WDW · An iconic Galaxy's Edge food"},
     {n:'Blue Milk',w:"Black Spire Outpost, Galaxy's Edge",p:'$~8',nt:"Frozen plant-based blue milk from the original trilogy · A must-try · Also available in green"},
     {n:'Carrot Cake Cookie',w:'Trolley Car Café (Starbucks)',p:'$~6',nt:'Two spiced cake cookies + cream cheese frosting · A Disney Food Blog legend'},
     {n:"Jack-Jack's Cookie Num Nums",w:'Pixar Place',p:'$~4',nt:"Snickerdoodle cookies · She'll recognise Jack-Jack from The Incredibles"},
     {n:"Outpost Mix Popcorn",w:"Galaxy's Edge carts",p:'$~5',nt:"Seasoned popcorn in collectible themed buckets · Great walk-around snack"},
   ],
   rests:[
     {n:"Oga's Cantina",t:'ts',p:'~$60–$90 (drinks/apps)',nt:"Galaxy's Edge · The most unique bar at WDW · Alien DJ R-3X spins music · Standing room · 45-min table limit · Reservations essential · Adults will love this · Not a full meal"},
     {n:'Docking Bay 7 Food and Cargo',t:'qs',p:'~$65–$80',nt:"Galaxy's Edge · Best QS in Hollywood Studios · All dishes themed to Batuu · Smoked Kaadu Ribs, Braised Shaak, Fried Endorian Tip-Yip"},
     {n:"50's Prime Time Café",t:'ts',p:'~$100–$140',nt:"Servers act like your mom — hilarious and very family-friendly · Kids love the retro TV screens · One of the most fun dining experiences at WDW"},
     {n:"Woody's Lunch Box",t:'qs',p:'~$50–$60',nt:"Best QS in Toy Story Land · Grilled cheese, s'mores french toast · Quick and great for a hungry family"},
   ],
   shops:[
     {section:"Galaxy's Edge — Star Wars"},
     {n:"Savi's Workshop",nt:"Build a custom lightsaber · $269.99 · Choose your hilt and kyber crystal · One of the most immersive experiences at any theme park · ~20 minutes · Reserve well in advance — books up fast"},
     {n:"Droid Depot",nt:"Build your own BB-unit or R-unit droid · ~$119.99 · It rolls alongside you and interacts with panels throughout Galaxy's Edge · Great for the whole family"},
     {n:"Dok-Ondar's Den of Antiquities",nt:"Best Star Wars shop at WDW · Ancient Sith and Jedi artifacts, Holocrons, rare lightsabers, collector-grade items · A serious shop for serious fans"},
     {n:"Black Spire Outpost market stalls",nt:"Multiple market stalls throughout Galaxy's Edge · Star Wars clothing, pins, accessories, droids, and Batuu-themed gear · The whole land feels like a real alien market"},
     {n:"Resistance Supply / First Order Cargo",nt:"Two rival faction shops facing each other · Pick a side · Resistance and First Order apparel, helmets, and accessories"},
     {section:'For your little girl'},
     {n:'Toy Story Land merch',nt:"Woody, Jessie, Buzz plush and clothing · She'll want everything in the land"},
     {n:'Disney Junior merchandise',nt:"Near Mickey & Minnie's · Current kids' TV characters she may know"},
   ]
  },
  {id:'ak',maps:{official:'https://mickeyvisit.com/disney-world-animal-kingdom-map/',pdf:'https://mickeyvisit.com/disney-world-animal-kingdom-map/',gmaps:'https://maps.google.com/maps?q=Disney+Animal+Kingdom+Walt+Disney+World+Orlando+FL&output=embed&z=16'},name:'Animal Kingdom',
   tag:'Real safari · Pandora · Tropical Americas opens 2027 — new Indiana Jones + Encanto rides',
   hbg:'#6457A6',htxt:'#ffffff',
   pills:['Safari (no height req)',"Na'vi River Journey",'Pandora at night'],
   age:"Animal Kingdom is excellent for almost-4. Real animals need no age minimum. Na'vi River Journey is gentle and gorgeous. Festival of the Lion King is a full Broadway show she will be captivated by. Go on the safari first — animals are most active in the morning.",
   coming:"Tropical Americas (Pueblo Esperanza) opens in 2027 — it WILL be open for your 2029 trip! This brand-new land replaces DinoLand U.S.A. and includes: a new Indiana Jones attraction (rethemed from the old DINOSAUR ride), a new Encanto-themed ride, a large central fountain, a major new quick-service restaurant, and a carousel featuring Disney animals. By 2029 this will likely be one of the most-talked-about new areas in any Disney park. Factor it into your Animal Kingdom day plan.",
   day:["Rope drop → Kilimanjaro Safaris immediately — animals most active in the morning · You'll get the best sightings","Na'vi River Journey (gentle, no height req, short wait right after rope drop)",'Mid-morning: Festival of the Lion King show — arrive 30 mins early · Do not miss this','Afternoon: Avatar Flight of Passage via Lightning Lane Single Pass · Finding Nemo show · Explore Tropical Americas (new 2027 land)','Wander Pandora as the light changes in late afternoon'],
   night:['Pandora bioluminescence — the land glows blue, purple, and teal after dark · Most magical after 8pm (your couples\' date night)','Tree of Life illuminated with animal projections — stand still and watch the shapes move','Animal Kingdom closes earlier than other parks — plan your evening timing carefully'],
   rAll:[
     {n:'Kilimanjaro Safaris',nt:'No height req · Real giraffes, elephants, lions, rhinos · At almost 4 this is pure wonder · Morning is essential'},
     {n:"Na'vi River Journey",nt:'No height req · Gentle glowing boat through Pandora · She will be completely enchanted'},
     {n:'Festival of the Lion King',nt:'Show · No height req · Full Broadway-quality production · Grandma and little one equally love this'},
     {n:'Finding Nemo: The Big Blue...and Beyond!',nt:'Show · No height req · Aquarium setting · Very accessible · Good afternoon rest option'},
     {n:'Tropical Americas rides (opening 2027)',nt:'New Indiana Jones attraction + new Encanto ride · Both expected to have family-friendly height requirements · Will be open for your 2029 trip · Details TBC'},
   ],
   snacks:[
     {n:'Night Blossom',w:'Pongu Pongu, Pandora',p:'$~7',nt:"Frozen limeade + passion fruit boba · She'll love the colours and boba balls · Rum Blossom for adults"},
     {n:'Blueberry Cream Cheese Mousse',w:"Satu'li Canteen",p:'$~6',nt:'Served in an alien pod shape · Instagram-worthy and genuinely delicious'},
     {n:'Churros',w:'Nomad Lounge',p:'$~10',nt:'Best churros at WDW · Two dipping sauces · Pair with a cocktail for the adults'},
     {n:'Pongu Lumpia',w:'Pongu Pongu',p:'$~4',nt:'Warm pineapple cream cheese spring roll · Unique to Pandora'},
   ],
   rests:[
     {n:"Satu'li Canteen",t:'qs',p:'~$60–$75',nt:'Best quick service at Disney World · Customisable grain bowls · Beautiful Pandora theming'},
     {n:'Tusker House',t:'ts',p:'~$140–$180',nt:'Donald Duck + Mickey in safari gear · African buffet · Buffet great for picky almost-4-year-olds'},
     {n:'Tiffins',t:'ts',p:'~$160–$220',nt:'Signature of Animal Kingdom · Sophisticated and quiet · Best adult dining in AK · Nomad Lounge next door needs no reservation'},
   ],
   shops:[
     {section:'For your little girl'},
     {n:'Windtraders — Pandora',nt:'Interactive banshee shoulder puppet (~$75) · Moves, flaps wings, responds to touch · The toy of this trip · At almost 4 she will be obsessed'},
     {n:"Colors of Mo'ara — Pandora",nt:"Na'vi face painting · She'll feel like she's really on Pandora · Great photos"},
     {n:'Discovery Trading Company',nt:'Best general merch in AK · Animal plush · Great for a stuffed giraffe after the safari'},
     {section:'For adults'},
     {n:'Mombasa Marketplace — Africa',nt:'Beautiful African artwork, carvings, and jewellery · Genuinely good quality · Best adult shop at AK'},
     {n:'Windtraders — Pandora',nt:'Avatar merchandise, glow-in-dark items, science kits'},
   ]
  }
];

